---
- name: Configure hosts & deploy application
  hosts: all
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
    
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
        tags: db-tag
        notify: restart mongod
  handlers: # ADD handlers and tasks
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
